language: minimal
env:
  global:
    - IMAGE_TAG=$TRAVIS_COMMIT

services:
  - docker

stages:
  - name: Build
  - name: Test

jobs:
  include:
    - stage: Build
      name: "Build"
      script: make build
    - stage: Test
      name: "Unit Tests"
      script: make unit_test

